export const customerLoginButton = '.borderM > :nth-child(1) > .btn'
export const homeButton = '.home'
export const selectCustomer = '#userSelect'
export const loginButton = 'form.ng-valid > .btn'
export const welcomeText = '.borderM > :nth-child(1) > strong'
export const valueofCurrency = '#accountSelect'