export const managerLoginButton = '.borderM > :nth-child(3) > .btn'
export const homeButton = '.home'
export const homepage = '.ng-scope'
export const addCustomerButton = '[ng-class="btnClass1"]'
export const openAccountButton = '[ng-class="btnClass2"]'
export const customerButton = '[ng-class="btnClass3"]'